theme: jekyll-theme-minimal
title: Margarida Rosa 
<img width="200" alt="Screenshot 2022-09-18 at 11 11 49" src="https://user-images.githubusercontent.com/99993156/190914287-2208d9af-27f7-45b5-ae61-b810c7462ee9.png">
description: Bookmark this to keep an eye on my project updates!
